### ISSUE TITLE
search & dataaudit_vacuum jobs

### ISSUE THREAD

**Issue by aligentjim** [vtsykun/mq-insight#14]
Hi Volodymyr,

Thanks for building mq-insight, it's an incredibly useful tool.

I'm curious about the `okvpn.message_processor.search_vacuum` and `okvpn.message_processor.dataaudit_vacuum` jobs in your sample screen shots.  I work for an Oro partner in Australia, and we've had some issues lately with duplicated search indexing jobs.  Especially after a large product/price import the system can spend many days reindexing the products hundreds of times over.  I'm interested to know whether this is the kind of problem that your queue jobs are trying to resolve, and if so whether you'd consider open sourcing the code or sharing it with us privately.

I know this isn't an issue with mq-insight as such, so feel free to delete this issue and email me directly at <redacted>.

Thanks,
Jim.

**Comment by vtsykun** [comment]
Hi @aligentjim 
No, it not resolve performance problem. In live demo to emulate message queue activity was created the cron job, that run a large contact import. But it requires a lot of free disk space, so to resolve disk space issue, was created processes to cleanup search and dataaudit tables.

As I know since 2.6.1 Oro team tried to fix reindex - now for one import chunk should will create only a one unique job on search_reindex (the job name `search_reindex|<hash>` in jobs datagrid) But It looks as bug in OroPlatform. In my demo I also noticed that the most of the time is spent on the dataaudit/search, therefore I set the lowest priority for search and dataaudit.
Also this problem can related with MQ performance degradation when a queue is large, see PR https://github.com/oroinc/platform/pull/767

Thanks,
Volodymyr.

**Comment by aligentjim** [comment]
We've definitely seen the performance issue with large queues (on both Postgres and MySQL).  We're also seeing issues with the search index reindexing the entire product database once for every combined price list (we have thousands of products, and hundreds of combined price lists, so that's obviously a problem).  We're working with Oro on a fix, but thought I'd reach out on the off chance you already had a work around.

Your open source stuff looks awesome, keep up the good work, and thanks for the help.

Jim.
